const products = [
  {
    key: "1",
    name: "Product 1",
    price: 10.0,
    in_stock: true,
    image: "image1.jpg",
    description: "Description for product 1",
  },
  {
    key: "2",
    name: "Product 2",
    price: 20.0,
    in_stock: false,
    image: "image2.jpg",
    description: "Description for product 2",
  },
  {
    key: "3",
    name: "Product 3",
    price: 30.0,
    in_stock: true,
    image: "image3.jpg",
    description: "Description for product 3",
  },
  {
    key: "4",
    name: "Product 4",
    price: 40.0,
    in_stock: true,
    image: "image4.jpg",
    description: "Description for product 4",
  },
  {
    key: "5",
    name: "Product 5",
    price: 50.0,
    in_stock: false,
    image: "image5.jpg",
    description: "Description for product 5",
  },
  {
    key: "6",
    name: "Product 6",
    price: 60.0,
    in_stock: true,
    image: "image6.jpg",
    description: "Description for product 6",
  },
  {
    key: "7",
    name: "Product 7",
    price: 70.0,
    in_stock: true,
    image: "image7.jpg",
    description: "Description for product 7",
  },
  {
    key: "8",
    name: "Product 8",
    price: 80.0,
    in_stock: false,
    image: "image8.jpg",
    description: "Description for product 8",
  },
  {
    key: "9",
    name: "Product 9",
    price: 90.0,
    in_stock: true,
    image: "image9.jpg",
    description: "Description for product 9",
  },
  {
    key: "10",
    name: "Product 10",
    price: 100.0,
    in_stock: true,
    image: "image10.jpg",
    description: "Description for product 10",
  },
];

export const getProducts = (req, res) => {
  res.json(products);
};
